### ISSUE TITLE
It would be nice to format the very large numbers representing ms so they're more readable. 

### ISSUE THREAD

**Issue by mircealungu** [mircealungu/automatic-monitoring-dasboard#12]
<img width="395" alt="screenshot 2017-06-01 22 20 12" src="https://cloud.githubusercontent.com/assets/464519/26699042/967e661e-4718-11e7-8df7-e74cdf56375a.png">

**Comment by kloostert** [comment]
<img width="235" alt="schermafbeelding 2017-06-06 om 14 32 21" src="https://cloud.githubusercontent.com/assets/17165311/26829239/0b28f6f0-4ac5-11e7-9039-1e75c35b3ab0.png">
