### ISSUE TITLE
why is the dashboard menu always closing?

### ISSUE THREAD

**Issue by mircealungu** [mircealungu/automatic-monitoring-dasboard#13]
It should stay open once i've selected 'measurements' from the navigation menu. In fact it should also highlight the current open page. 

in fact it should open by default on the 'measurements' page, because this is what i care about in the first place! once there are measurements set up, i don't want to read again about how to use the dashboard ;)

**Comment by FlyingBird95** [comment]
I removed the installing and configuration page

**Comment by kloostert** [comment]
Menu also stays open after link click.
Menu now highlights current open page.
Opens by default on the measurements page.

**Comment by kloostert** [comment]
Small remark: in order for the changes in the JS files to come into effect, you might need to clear the cached version of the (old) JS files from your browser.
