### ISSUE TITLE
setup.py should be in the root of the repository

### ISSUE THREAD

**Issue by mircealungu** [mircealungu/automatic-monitoring-dasboard#17]
guys,

the Zeeguu-API automated testing breaks now since it has a dependency to the dashboard. 

It turns out that for Travis / pip to be able to automatically pull a library from github the setup.py should be in the root of the project. 

so if you could make this happen it would be great!

**Comment by kloostert** [comment]
I moved the setup.py (with some minor changes) to the root of the repo just now.
I hope this will resolve the Travis issue.

**Comment by mircealungu** [comment]
Thanks.
Please do send a pull request to master.

M.
