### ISSUE TITLE
error on the /measurements page

### ISSUE THREAD

**Issue by mircealungu** [mircealungu/automatic-monitoring-dasboard#4]
a fragment from the log on the server: 
```
[Tue May 30 14:20:29.012349 2017] [wsgi:error] [pid 25729:tid 140150059906816] [remote 145.90.134.187:47175]     <td><a href="{{ url_for('dashboard.show_graph', endpoint=record.endpoint) }}">Show graph</a></td>
[Tue May 30 14:20:29.012376 2017] [wsgi:error] [pid 25729:tid 140150059906816] [remote 145.90.134.187:47175] TypeError: url_for() got multiple values for argument 'endpoint'

```

<img width="1170" alt="screenshot 2017-05-30 14 21 44" src="https://cloud.githubusercontent.com/assets/464519/26582952/583c7f34-4543-11e7-91f1-47409dfcab3c.png">

**Comment by FlyingBird95** [comment]
Solved, see my last commit: https://github.com/mircealungu/automatic-monitoring-dasboard/pull/3/commits/bad4c873098d96eb80f92b85aeff01c7be5263e9
