### ISSUE TITLE
remove IDE files from version control

### ISSUE THREAD

**Issue by mircealungu** [mircealungu/automatic-monitoring-dasboard#5]
.idea/automatic-monitoring-dasboard.iml        |  19 +++++
 .idea/inspectionProfiles/profiles_settings.xml |   7 ++
 .idea/misc.xml                                 |   4 +
 .idea/modules.xml                              |   8 ++
 .idea/vcs.xml                                  |   6 ++
 .idea/workspace.xml                            | 453 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

**Comment by FlyingBird95** [comment]
updated gitignore, fixed issue
